In [1]:
import numpy as np

In [4]:
mat = np.random.rand(3,3)

In [8]:
mat = np.ceil(mat * 10)

In [9]:
mat

array([[ 7.,  8.,  1.],
       [ 8.,  4.,  5.],
       [ 1.,  9.,  4.]])

In [37]:
mat = np.array([[1,2,3],[2,3,4],[3,4,5],[4,5,6]])
mat

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [38]:
mat + 3

array([[4, 5, 6],
       [5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [39]:
mat + [1, 2, 3]

array([[2, 4, 6],
       [3, 5, 7],
       [4, 6, 8],
       [5, 7, 9]])

In [43]:
mat + np.matrix([1,2,3,4]).T 
# note that np.array doesn't do the trick (it doesn't transpose). 
# For np.array to work need to use 'newaxis'

matrix([[ 2,  3,  4],
        [ 4,  5,  6],
        [ 6,  7,  8],
        [ 8,  9, 10]])

In [45]:
mat * [1,2,3]

array([[ 1,  4,  9],
       [ 2,  6, 12],
       [ 3,  8, 15],
       [ 4, 10, 18]])

In [46]:
np.mean(mat,axis=1)

array([ 2.,  3.,  4.,  5.])

In [62]:
list([0]).append(range(2,17))